# Generated by Django 4.2.19 on 2025-02-07 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='todos',
            new_name='Todo',
        ),
    ]
