# Generated by Django 4.2.19 on 2025-02-07 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0002_rename_todos_todo'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='body',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
